; See oidos.h for documentation.

%include "platform.inc"

; Functions
extern PUBLIC_SYM(Oidos_FillRandomData)
extern PUBLIC_SYM(Oidos_GenerateMusic)
extern PUBLIC_SYM(Oidos_StartMusic)
extern PUBLIC_SYM(Oidos_GetPosition)

; Variables
extern PUBLIC_SYM(Oidos_MusicBuffer)
extern PUBLIC_SYM(Oidos_TicksPerSecond)
extern PUBLIC_SYM(Oidos_MusicLength)
extern PUBLIC_SYM(Oidos_WavFileHeader)
extern PUBLIC_SYM(Oidos_RandomData)

; GUID
extern ID3D11Texture2D_ID
extern ?ID3D11Texture2D_ID@@3U_GUID@@A
