[package]
name = "Oidos"
version = "2.1.0"
authors = ["Aske Simon Christensen <blueberry@loonies.dk>"]
build = "build.rs"

[dependencies]
vst = "0.2.0"

[dev-dependencies]
rand = "0.4"

[build-dependencies]
nasm-rs = "= 0.1.3"

[lib]
name = "Oidos"
crate-type = ["cdylib"]
